let nombre = prompt ("Ingresa tu nombre")
let apellido = prompt ("Ingresa tu Apellido")
let Edad = prompt ("Ingresa tu Edad")
let Nacionalidad = prompt ("Ingresa tu Nacionalidad")
let Documento = prompt ("Ingresa tu documento")
alert(`Nuevo usuario ingresado al sistema ${nombre}, ${apellido}, ${Edad}, ${Nacionalidad} y ${Documento}`)
